Documentation:
  Enabled: false

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 99
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'

Style/ModuleFunction:
  Enabled: false

Metrics/ClassLength:
  Max: 179

Metrics/ModuleLength:
  Max: 150

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
